// fake data
const customers = [
  {
    id: 1,
    name: 'Seytechdata',
    lastName: 'Co',
    avatar: 'https://www.seytech.co/images/logo.png',
    email: 'support@seytech.co',
    state: 'WA',
    phone: 1234567703,
    role: 'student',
    github: 'githubtes',
    courses: ['js, react, algo'],
    payment: 12000,
  },
  {
    id: 2,
    name: 'Eliza',
    lastName: 'Co',
    avatar: 'https://avatars1.githubusercontent.com/u/68719361?s=100&v=4',
    email: 'support@seytech.co',
    state: 'WA',
    phone: 1234567703,
    role: 'student',
    github: 'ewrg',
    courses: ['js, react, algo'],
    payment: 12000,
  },
  {
    id: 3,
    name: 'Adilet',
    lastName: 'Co',
    avatar: 'https://avatars0.githubusercontent.com/u/55602501?s=100&v=4',
    email: 'support@seytech.co',
    state: 'WA',
    phone: 1234567703,
    role: 'instructor',
    github: 'asdsf',
    courses: ['js, react, algo'],
    payment: 12000,
  },
  {
    id: 4,
    name: 'Max',
    lastName: 'Co',
    avatar: 'https://avatars0.githubusercontent.com/u/40704457?s=100&v=4',
    email: 'support@seytech.co',
    state: 'WA',
    phone: 1234567703,
    role: 'student',
    github: 'lkdfg',
    courses: ['js, react, algo'],
    payment: 12000,
  },
  {
    id: 5,
    name: 'Ulan',
    lastName: 'Co',
    avatar: 'https://avatars1.githubusercontent.com/u/16879917?s=100&v=4',
    email: 'support@seytech.co',
    state: 'WA',
    phone: 1234567703,
    role: 'admin',
    github: 'efgdd',
    courses: ['js, react, algo'],
    payment: 12000,
  },
];
